### ISSUE TITLE
Problème compilation TELEMAC

### ISSUE THREAD

**Issue by paulgirardot** [snale-net/pagure#31]
Bonjour, 

Je souhaite compiler TELEMAC avec PAGURE sur un cluster pour utiliser la version v8p5. Pour cela j'ai récupéré la dernière version de pagure.

1) Je charge les modules suivants :  use.own  cv-standard   gcc/7.5.0 

2) Puis je lance la commande suivantes pour compiler TELEMAC avec Pagure : ./pagure.sh --prefix=/home/e_gcl-17/softs --system=cluster --compiler=gnu --filter=TELEMAC --module-dir=/home/e_gcl-17/privatemodules

J'obtiens une erreur qui m'indique que le module 'udunits/gcc75/2.2.28' est manquant. Je ne trouve pas la démarche à suivre pour ajouter ce module. J'ai ajouter le log en PJ.

Merci d'avance pour votre aide.

Paul
[pagure.log](https://github.com/user-attachments/files/16378574/pagure.log)

**Comment by fretif** [comment]
Bonjour Paul,

Je viens de pousser un correctif avec une mise à jour des dépendances pour TELEMAC : bfb3171

**Comment by paulgirardot** [comment]
Merci beaucoup.

Je relance ça lundi prochain.

Le ven. 26 juil. 2024 à 16:30, Fabien Rétif ***@***.***> a
écrit :

**Comment by paulgirardot** [comment]
Bonjour, 

Il reste encore un soucis avec med 4.0.0.
Je met le log en pièce jointe.  

Cordialement,
[pagure.log](https://github.com/user-attachments/files/16413879/pagure.log)


Paul GIRARDOT

**Comment by fretif** [comment]
L'url est down. J'ai mis à jour les URL pour MED et MUMPS : fc9407e

**Comment by fretif** [comment]
reopen

**Comment by paulgirardot** [comment]
Bonjour Fabien, 

PAGURE a correctement terminé (je mets le log en PJ).
Cependant, il n'y a pas de module nommé TELEMAC qui est installé comme ça peut être le cas pour SWAN ou XBEACH.

Faut il ensuite réaliser la compilation de TELEMAC à la main ? en :
- chargeant les modules installés par pagure
- récupérant le Dépôt TELEMAC
- puis en compilant (compile_telemac.py --clean)

Merci d'avance. 

Paul

**Comment by fretif** [comment]
Oui il faut compiler TELEMAC à la main en se reportant aux instructions : https://hydro-informatics.com/get-started/install-telemac.html#compile-telemac
Le modèle n'étant pas disponible au téléchargement sans compte, PAGURE installe uniquement les dépendances.

**Comment by paulgirardot** [comment]
D'accord, très bien c'est ce que je tente de réaliser :

1) Je charge l'ensemble des modules fournis par PAGURE :
- cmake 3.20.5
- lapack-blas 3.9.1
- openmpi 1.10.7
- scalapack 2.1.0
- zlib 1.2.11 
- parallel-netcdf 1.12.1
- hdf5 1.10.5
- netcdf 4.8.0 
- netcdf 4.5.3
- med 4.0.0
- aed2 1.3.0
- metis 5.1.0
- parmetis 4.0.3
- scotch 6.0.9 
- ptscotch 6.0.9 
- mumps 5.2.1 

2) Je définis les emplacement des installations de med et hdf5 (sinon la compilation échoue)
->   export HDF5HOME=/nfs/home/e_gcl-17/softs/hdf5/openmpi110/gcc75/1.10.5
->   export MEDHOME=/nfs/home/e_gcl-17/softs/med/openmpi110/gcc75/4.0.0

3) Je lance la compilation : 
-> cd ~/telemac/configs
-> source pysource.gfortranHPC.sh
-> config.py
-> compile_telemac.py --clean

4) La compilation se termine correctement (par "My work is done")

5)  Je teste Telemac et ça plante :
-> cd ~/telemac/examples/telemac2d/gouttedo
-> telemac2d.py t2d_gouttedo.cas


  J'obients cette erreur :

**Comment by paulgirardot** [comment]
Loading Options and Configurations
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

                    _
                   (_)
  _ __ ___    __ _  _  _ __
 | '_ ` _ \  / _` || || '_ \
 | | | | | || (_| || || | | |
 |_| |_| |_| \__,_||_||_| |_|




Running your CAS file(s) for:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

S10.gfortran.dyn:


    +> Scibian 10 dynamic build using GFortran 8.3.0 and Open MPI.

    +> root:    /home/e_gcl-17/telemac/telemac-mascaret
    +> module: ad / api / artemis / bief
               damocles  / gaia  / gretel  / hermes
               identify_liq_bnd  / khione  / mascaret  / nestor
               parallel  / partel  / postel3d  / special
               stbtel  / telemac2d  / telemac3d  / tomawac
               waqtel


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


... processing the steering file
  ~> Checking keyword/rubrique coherence

... checking parallelisation

... handling temporary directories
         copying: t2d_gouttedo.cas -> /nfs<root>/examples/telemac2d/gouttedo/t2d_gouttedo.cas_2024-08-02-12h19min09s/T2DCAS
         copying: telemac2d.dico -> /nfs<root>/examples/telemac2d/gouttedo/t2d_gouttedo.cas_2024-08-02-12h19min09s/T2DDICO
         copying: geo_gouttedo.cli -> /nfs<root>/examples/telemac2d/gouttedo/t2d_gouttedo.cas_2024-08-02-12h19min09s/T2DCLI
         copying: geo_gouttedo.slf -> /nfs<root>/examples/telemac2d/gouttedo/t2d_gouttedo.cas_2024-08-02-12h19min09s/T2DGEO

... checking the executable
  > compiling objs
         compiling: user_condin_h.f ... completed
         compiling: user_condin_trac.f ... completed
         created: out_user_fortran


Running your simulation(s) :
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



In /nfs/home/e_gcl-17/telemac/telemac-mascaret/examples/telemac2d/gouttedo/t2d_gouttedo.cas_2024-08-02-12h19min09s:
mpirun -np 1 /nfs/home/e_gcl-17/telemac/telemac-mascaret/examples/telemac2d/gouttedo/t2d_gouttedo.cas_2024-08-02-12h19min09s/out_user_fortran


 MASTER PROCESSOR NUMBER            0  OF THE GROUP OF            1
 EXECUTABLE FILE: /nfs/home/e_gcl-17/telemac/telemac-mascaret/examples/telemac2d/gouttedo/t2d_gouttedo.cas_2024-08-02-12h19min09s/A.EXE
 LISTING OF TELEMAC2D------------------------------------------------------------------------------

                TTTTT  EEEEE  L      EEEEE  M   M  AAAAA  CCCCC
                  T    E      L      E      MM MM  A   A  C
                  T    EEE    L      EEE    M M M  AAAAA  C
                  T    E      L      E      M   M  A   A  C
                  T    EEEEE  LLLLL  EEEEE  M   M  A   A  CCCCC

                        2D    VERSION MAIN   FORTRAN 2003

                        ~^~^~^~^~^~^~^~^~^~^~^^~^~^~^~^~^~
                          ~                            ~
                               \   '    o      '
                               /\ o       \  o
                             >=)'>    '   /\ '
                               \/   \   >=)'>        ~
                               /    /\    \/
                        ~         >=)'>   /     .
                                    \/                   )
                                    /                   (
                                          ~          )   )
                          }     ~              (    (   (
                         {                      )    )   )
                          }  }         .       (    (   (
                         {  {               /^^^^^^^^^^^^
                        ^^^^^^^^^\         /
                                  ^^^^^^^^^

 DIFFERENT NUMBER OF PARALLEL PROCESSORS:
 DECLARED BEFORE (CASE OF COUPLING ?):           1
 TELEMAC-2D :           0
 VALUE            1  IS KEPT

                   ********************************************
                   *               LECDON:                    *
                   *        AFTER CALLING DAMOCLES            *
                   *        CHECKING OF DATA  READ            *
                   *         IN THE STEERING FILE             *
                   ********************************************

 EXITING LECDON. NAME OF THE STUDY:
 TELEMAC 2D: DROPLET IN A BASIN

 OPENING FILES FOR TELEMAC2D
 OPENING: T2DGEO-geo_gouttedo.slf
 ERROR         1016 DURING CALL OF BIEF_OPEN_FILES:OPEN_MESH
 ERROR TEXT: HERMES_INVALID_SERAFIN_FILE
 ERROR IN /nfs/home/e_gcl-17/telemac/telemac-mascaret/examples/telemac2d/gouttedo/t2d_gouttedo.cas_2024-08-02-12h19min09s/T2DGEO: IDENTIFY_ENDIAN_TYPE:READ:LITTLE_ENDIAN

 PLANTE: PROGRAM STOPPED AFTER AN ERROR
 RETURNING EXIT CODE:            2
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 2.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[7557,1],0]
  Exit code:    2
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/e_gcl-17/telemac/telemac-mascaret/scripts/python3/telemac2d.py", line 7, in <module>
    main('telemac2d')
  File "/nfs/home/e_gcl-17/telemac/telemac-mascaret/scripts/python3/runcode.py", line 288, in main
    run_study(cas_file, code_name, options)
  File "/nfs/home/e_gcl-17/telemac/telemac-mascaret/scripts/python3/execution/run_cas.py", line 169, in run_study
    run_local_cas(my_study, options)
  File "/nfs/home/e_gcl-17/telemac/telemac-mascaret/scripts/python3/execution/run_cas.py", line 65, in run_local_cas
    my_study.run(options)
  File "/nfs/home/e_gcl-17/telemac/telemac-mascaret/scripts/python3/execution/study.py", line 659, in run
    self.run_local()
  File "/nfs/home/e_gcl-17/telemac/telemac-mascaret/scripts/python3/execution/study.py", line 480, in run_local
    run_code(self.run_cmd, self.sortie_file)
  File "/nfs/home/e_gcl-17/telemac/telemac-mascaret/scripts/python3/execution/run.py", line 182, in run_code
    raise TelemacException('Fail to run\n'+exe)
utils.exceptions.TelemacException: Fail to run
mpirun -np 1 /nfs/home/e_gcl-17/telemac/telemac-mascaret/examples/telemac2d/gouttedo/t2d_gouttedo.cas_2024-08-02-12h19min09s/out_user_fortran

**Comment by paulgirardot** [comment]
Sais tu comment résoudre ce problème ?
Merci à toi.
Paul

**Comment by fretif** [comment]
C'est sûrement un problème de configuration : 
ERROR TEXT: HERMES_INVALID_SERAFIN_FILE
ERROR IN /nfs/home/e_gcl-17/telemac/telemac-mascaret/examples/telemac2d/gouttedo/t2d_gouttedo.cas_2024-08-02-12h19min09s/T2DGEO: IDENTIFY_ENDIAN_TYPE:READ:LITTLE_ENDIAN

Il vaut mieux poster ton erreur sur le forum de TELEMAC.

Après je vois que tu as compilé TELEMAC avec GNU 8.3.0 alors que tu as utilisé GNU 7.5.0 pour les librairies.
Idéalement, c'est mieux de tout compiler avec la même version.

**Comment by paulgirardot** [comment]
Je reprend depuis la source.
Je vais utiliser GNU 8.5.0 pour les librairies, puis compiler TELEMAC avec.

Cependant PAGRE plante lors de l'installation des librairies avec GNU 8.5.0 :

[  INFO  ]  Install scotch 6.0.9 (sequential version)
--2024-08-02 16:02:39--  https://gforge.inria.fr/frs/download.php/file/38187/scotch_6.0.9.tar.gz
Resolving gforge.inria.fr (gforge.inria.fr)... failed: Name or service not known.
wget: unable to resolve host address 'gforge.inria.fr'
[  ABORT  ] PAGURE aborted with status error 4


Je met le log en PJ.




[pagure.log](https://github.com/user-attachments/files/16471468/pagure.log)

**Comment by fretif** [comment]
C'est une erreur de récupération des sources : wget: unable to resolve host address 'gforge.inria.fr'
Il suffit sûrement relancer PAGURE.
